#include "engine/unit_types.h"

#include "engine/structures.h"

#include <iterator>

namespace engine {

namespace {

// Stats are written in human units (tiles, seconds) and converted to ticks here.
constexpr Fixed tiles(int32_t num, int32_t den = 1) { return Fixed::from_ratio(num, den); }
constexpr Fixed tiles_per_second(int32_t num, int32_t den = 1) {
    return Fixed::from_ratio(num, den * kTicksPerSecond);
}
constexpr Tick seconds(int32_t num, int32_t den = 1) { return static_cast<Tick>(num * kTicksPerSecond / den); }

constexpr Fixed kInstantHit{};
constexpr Fixed kNoSplash{};

// Armor is {Bullet, Explosive, AntiTank}.
// Balance numbers are a first draft; the relations matter more than values:
//   machine gun   shreds infantry, useless against armor
//   RPG           slow, dodgeable rocket that cracks armor
//   tank          kills anything, but reloads slowly and its shells can be dodged at range
//   IFV           fast, light armor, autocannon great against infantry
//   rear trooper  gathers, builds and unloads; can be retrained as a rifleman
//   scout         makes out men in cover from farther away, hard to spot himself; as an
//                 observation post watches a sector far out
// Costs are {Personnel, Food, Materials, Ammo, Fuel}. Men are the scarce one.
constexpr UnitTypeDef kUnitTypes[] = {
    {
        .name = "Rifleman",
        .short_name = "RIF",
        .max_hp = 40,
        .armor = {0, 0, 45},
        .speed = tiles_per_second(1),
        .radius = tiles(1, 5),
        .sight = tiles(7),
        .mass = 1,
        .vehicle = false,
        .weapon = {.name = "Assault rifle", .damage = 6, .damage_type = DamageType::Bullet,
                   .range = tiles(5), .reload = seconds(1), .projectile_speed = kInstantHit,
                   .splash_radius = kNoSplash, .accuracy = 70, .miss_spread = tiles(1)},
        .cost = {1, 25, 0, 20, 0},
        .train_time = seconds(12),
        .rounds_capacity = 120,
        .rounds_per_supply = 30,
        .abilities = {AbilityId::DigTrench, AbilityId::DigFoxhole, AbilityId::BuildParapet},
        .ability_count = 3,
    },
    {
        .name = "Machine gunner",
        .short_name = "MG",
        .max_hp = 45,
        .armor = {0, 0, 45},
        .speed = tiles_per_second(4, 5),
        .radius = tiles(1, 5),
        .sight = tiles(7),
        .mass = 1,
        .vehicle = false,
        .weapon = {.name = "Machine gun", .damage = 3, .damage_type = DamageType::Bullet,
                   .range = tiles(6), .reload = seconds(1, 4), .projectile_speed = kInstantHit,
                   .splash_radius = kNoSplash, .accuracy = 55, .miss_spread = tiles(1)},
        .cost = {1, 25, 0, 40, 0},
        .train_time = seconds(15),
        .rounds_capacity = 500,
        .rounds_per_supply = 50,
    },
    {
        .name = "Grenadier",
        .short_name = "RPG",
        .max_hp = 40,
        .armor = {0, 0, 45},
        .speed = tiles_per_second(19, 20),
        .radius = tiles(1, 5),
        .sight = tiles(6),
        .mass = 1,
        .vehicle = false,
        // Twice a rifleman's reach; two hits knock a tank out, one in the side or the rear.
        .weapon = {.name = "RPG-7", .damage = 200, .damage_type = DamageType::AntiTank,
                   .range = tiles(10), .reload = seconds(5), .projectile_speed = tiles_per_second(6),
                   .splash_radius = kNoSplash, .accuracy = 85, .miss_spread = tiles(3, 2),
                   .structure_damage = 80},
        .cost = {1, 25, 0, 60, 0},
        .train_time = seconds(15),
        .rounds_capacity = 6,
    },
    {
        .name = "Tank",
        .short_name = "TNK",
        .max_hp = 360,
        .armor = {40, 20, 20},
        .speed = tiles_per_second(11, 10),
        .radius = tiles(9, 20),
        .sight = tiles(12),
        .mass = 30,
        .vehicle = true,
        // Ten times a rifleman's reach; far out it's less sure (see effective_range),
        // and it takes someone seeing that far.
        .weapon = {.name = "125mm HE shell", .damage = 75, .damage_type = DamageType::Explosive,
                   .range = tiles(50), .reload = seconds(4), .projectile_speed = tiles_per_second(14),
                   .splash_radius = tiles(1, 2), .accuracy = 80, .miss_spread = tiles(1),
                   .effective_range = tiles(15)},
        .cost = {3, 0, 150, 100, 100},
        .train_time = seconds(40),
        .fuel_capacity = tiles(150),
        .rounds_capacity = 40,
        // Armor-piercing: a fast, hard-hitting round without a burst.
        .alt_weapon = {.name = "125mm AP round", .damage = 130, .damage_type = DamageType::AntiTank,
                       .range = tiles(50), .reload = seconds(4), .projectile_speed = tiles_per_second(24),
                       .splash_radius = kNoSplash, .accuracy = 85, .miss_spread = tiles(1),
                       .effective_range = tiles(15)},
        .abilities = {AbilityId::AreaShot, AbilityId::SwitchAmmo, AbilityId::IndirectFire, AbilityId::Smoke,
                      AbilityId::RadioSilence, AbilityId::CallSupply},
        .ability_count = 6,
        .emitter = true,
    },
    {
        .name = "IFV",
        .short_name = "IFV",
        .max_hp = 220,
        .armor = {8, 8, 5},
        .speed = tiles_per_second(7, 5),
        .radius = tiles(2, 5),
        .sight = tiles(8),
        .mass = 15,
        .vehicle = true,
        .weapon = {.name = "30mm autocannon", .damage = 14, .damage_type = DamageType::Bullet,
                   .range = tiles(6), .reload = seconds(3, 5), .projectile_speed = tiles_per_second(25),
                   .splash_radius = kNoSplash, .accuracy = 70, .miss_spread = tiles(1)},
        .cost = {3, 0, 100, 60, 80},
        .train_time = seconds(30),
        .fuel_capacity = tiles(180),
        .rounds_capacity = 150,
        .rounds_per_supply = 5,
        .troop_capacity = 7,
        .missile_capacity = 4,
        .abilities = {AbilityId::MgSweep, AbilityId::LobGrenade, AbilityId::RadioSilence, AbilityId::CallSupply,
                      AbilityId::Atgm},
        .ability_count = 5,
        .emitter = true,
    },
    {
        .name = "Rear trooper",
        .short_name = "REAR",
        .max_hp = 30,
        .armor = {0, 0, 45},
        .speed = tiles_per_second(1),
        .radius = tiles(1, 5),
        .sight = tiles(6),
        .mass = 1,
        .vehicle = false,
        .weapon = {.name = "Carbine", .damage = 4, .damage_type = DamageType::Bullet,
                   .range = tiles(4), .reload = seconds(5, 4), .projectile_speed = kInstantHit,
                   .splash_radius = kNoSplash, .accuracy = 60, .miss_spread = tiles(1)},
        .cost = {1, 25, 0, 0, 0},
        .train_time = seconds(10),
        .worker = true,
        .rounds_capacity = 40,
        .rounds_per_supply = 20,
    },
    {
        // Unarmed and thin-skinned: the supply line is a target.
        .name = "Supply truck",
        .short_name = "TRK",
        .max_hp = 120,
        .armor = {3, 0, 0},
        .speed = tiles_per_second(9, 5),
        .radius = tiles(7, 20),
        .sight = tiles(6),
        .mass = 10,
        .vehicle = true,
        .wheeled = true,
        .weapon = {.name = "Unarmed", .damage = 0, .damage_type = DamageType::Bullet, .range = tiles(0),
                   .reload = seconds(1), .projectile_speed = kInstantHit, .splash_radius = kNoSplash,
                   .accuracy = 0, .miss_spread = tiles(0)},
        .cost = {1, 0, 50, 0, 30},
        .train_time = seconds(15),
    },
    {
        // Eyes, not firepower: a carbine for self-defence, binoculars for the rest.
        .name = "Scout",
        .short_name = "SCT",
        .max_hp = 35,
        .armor = {0, 0, 45},
        .speed = tiles_per_second(6, 5),
        .radius = tiles(1, 5),
        .sight = tiles(9),
        .mass = 1,
        .vehicle = false,
        .weapon = {.name = "Carbine", .damage = 5, .damage_type = DamageType::Bullet,
                   .range = tiles(5), .reload = seconds(5, 4), .projectile_speed = kInstantHit,
                   .splash_radius = kNoSplash, .accuracy = 65, .miss_spread = tiles(1)},
        .cost = {1, 25, 0, 15, 0},
        .train_time = seconds(15),
        .rounds_capacity = 60,
        .rounds_per_supply = 30,
        .detection = tiles(4),
        .stealthy = true,
        .sector_range = tiles(15),
    },
    {
        // Lighter than a rifleman, deadlier up close: storms trenches and houses.
        .name = "Assault trooper",
        .short_name = "AST",
        .max_hp = 32,
        .armor = {0, 0, 45},
        .speed = tiles_per_second(23, 20),
        .radius = tiles(1, 5),
        .sight = tiles(7),
        .mass = 1,
        .vehicle = false,
        .weapon = {.name = "Short assault rifle", .damage = 7, .damage_type = DamageType::Bullet,
                   .range = tiles(4), .reload = seconds(4, 5), .projectile_speed = kInstantHit,
                   .splash_radius = kNoSplash, .accuracy = 75, .miss_spread = tiles(1)},
        .cost = {1, 25, 0, 35, 0},
        .train_time = seconds(15),
        .rounds_capacity = 150,
        .rounds_per_supply = 30,
        .abilities = {AbilityId::ThrowGrenade},
        .ability_count = 1,
    },
    {
        // Thin-skinned and full of fuel: the enemy's favourite target.
        .name = "Fuel tanker",
        .short_name = "FUEL",
        .max_hp = 60,
        .armor = {0, 0, 0},
        .speed = tiles_per_second(8, 5),
        .radius = tiles(7, 20),
        .sight = tiles(6),
        .mass = 10,
        .vehicle = true,
        .wheeled = true,
        .weapon = {.name = "Unarmed", .damage = 0, .damage_type = DamageType::Bullet, .range = tiles(0),
                   .reload = seconds(1), .projectile_speed = kInstantHit, .splash_radius = kNoSplash,
                   .accuracy = 0, .miss_spread = tiles(0)},
        .cost = {1, 0, 60, 0, 40},
        .train_time = seconds(15),
        .supplies = Resource::Fuel,
        .cargo_capacity = 150,
        .abilities = {AbilityId::Refill},
        .ability_count = 1,
    },
    {
        .name = "Ammunition truck",
        .short_name = "AMMO",
        .max_hp = 100,
        .armor = {3, 0, 0},
        .speed = tiles_per_second(17, 10),
        .radius = tiles(7, 20),
        .sight = tiles(6),
        .mass = 10,
        .vehicle = true,
        .wheeled = true,
        .weapon = {.name = "Unarmed", .damage = 0, .damage_type = DamageType::Bullet, .range = tiles(0),
                   .reload = seconds(1), .projectile_speed = kInstantHit, .splash_radius = kNoSplash,
                   .accuracy = 0, .miss_spread = tiles(0)},
        .cost = {1, 0, 60, 20, 20},
        .train_time = seconds(15),
        .supplies = Resource::Ammo,
        .cargo_capacity = 100,
        .abilities = {AbilityId::Refill},
        .ability_count = 1,
    },
    {
        // Plunging fire: the one that finds men in trenches.
        .name = "Mortar crew",
        .short_name = "MOR",
        .max_hp = 45,
        .armor = {0, 0, 45},
        .speed = tiles_per_second(4, 5),
        .radius = tiles(1, 4),
        .sight = tiles(6),
        .mass = 2,
        .vehicle = false,
        .weapon = {.name = "82mm mortar bomb", .damage = 45, .damage_type = DamageType::Explosive,
                   .range = tiles(20), .reload = seconds(3), .projectile_speed = tiles_per_second(7),
                   .splash_radius = tiles(1), .accuracy = 100, .miss_spread = tiles(0), .indirect = true,
                   .min_range = tiles(3)},
        .cost = {2, 50, 0, 40, 0},
        .train_time = seconds(20),
        .rounds_capacity = 40,
        .abilities = {AbilityId::Deploy, AbilityId::DigGunPit, AbilityId::RadioSilence, AbilityId::CallSupply},
        .ability_count = 4,
        .deploy_time = seconds(3),
        .emitter = true,
    },
    {
        // Far-reaching and blind: it hits what someone else sees for it.
        .name = "Howitzer D-30",
        .short_name = "HOW",
        .max_hp = 160,
        .armor = {8, 10, 10},
        .speed = tiles_per_second(1),
        .radius = tiles(2, 5),
        .sight = tiles(5),
        .mass = 12,
        .vehicle = true,
        .wheeled = true,  // towed
        .weapon = {.name = "122mm HE shell", .damage = 110, .damage_type = DamageType::Explosive,
                   .range = tiles(60), .reload = seconds(6), .projectile_speed = tiles_per_second(9),
                   .splash_radius = tiles(3, 2), .accuracy = 100, .miss_spread = tiles(0), .indirect = true,
                   .min_range = tiles(5)},
        .cost = {4, 0, 150, 60, 30},
        .train_time = seconds(40),
        .rounds_capacity = 30,
        .abilities = {AbilityId::Deploy, AbilityId::DigGunPit, AbilityId::Camouflage, AbilityId::RadioSilence,
                      AbilityId::CallSupply},
        .ability_count = 5,
        .deploy_time = seconds(8),
        .emitter = true,
    },
    {
        // Grenades lobbed by the belt: over parapets, into trenches.
        .name = "AGS-17 crew",
        .short_name = "AGS",
        .max_hp = 45,
        .armor = {0, 0, 45},
        .speed = tiles_per_second(4, 5),
        .radius = tiles(1, 4),
        .sight = tiles(7),
        .mass = 2,
        .vehicle = false,
        .weapon = {.name = "30mm grenade", .damage = 20, .damage_type = DamageType::Explosive, .range = tiles(8),
                   .reload = seconds(1, 2), .projectile_speed = tiles_per_second(9), .splash_radius = tiles(4, 5),
                   .accuracy = 60, .miss_spread = tiles(3, 2), .lobbed = true},
        .cost = {2, 50, 0, 50, 0},
        .train_time = seconds(20),
        .rounds_capacity = 150,
        .rounds_per_supply = 5,
        .abilities = {AbilityId::RapidFire},
        .ability_count = 1,
    },
    {
        // Forty rockets in twenty seconds: an area, not a target.
        .name = "MLRS BM-21",
        .short_name = "MLRS",
        .max_hp = 140,
        .armor = {5, 0, 10},
        .speed = tiles_per_second(8, 5),
        .radius = tiles(2, 5),
        .sight = tiles(5),
        .mass = 12,
        .vehicle = true,
        .wheeled = true,
        .weapon = {.name = "122mm rocket", .damage = 55, .damage_type = DamageType::Explosive, .range = tiles(70),
                   .reload = seconds(1), .projectile_speed = tiles_per_second(12), .splash_radius = tiles(6, 5),
                   .accuracy = 100, .miss_spread = tiles(0), .indirect = true, .min_range = tiles(8)},
        .cost = {3, 0, 180, 80, 40},
        .train_time = seconds(45),
        .rounds_capacity = 40,
        .abilities = {AbilityId::Deploy, AbilityId::Salvo, AbilityId::RadioSilence, AbilityId::CallSupply},
        .ability_count = 4,
        .deploy_time = seconds(5),
        .emitter = true,
    },
    {
        // Mines, wire, hedgehogs, pillboxes and charges; finds the enemy's mines.
        .name = "Sapper",
        .short_name = "SAP",
        .max_hp = 40,
        .armor = {0, 0, 45},
        .speed = tiles_per_second(1),
        .radius = tiles(1, 5),
        .sight = tiles(7),
        .mass = 1,
        .vehicle = false,
        .weapon = {.name = "Carbine", .damage = 5, .damage_type = DamageType::Bullet, .range = tiles(4),
                   .reload = seconds(5, 4), .projectile_speed = kInstantHit, .splash_radius = kNoSplash,
                   .accuracy = 60, .miss_spread = tiles(1)},
        .cost = {1, 25, 20, 20, 0},
        .train_time = seconds(18),
        .engineer = true,
        .rounds_capacity = 60,
        .rounds_per_supply = 30,
        .abilities = {AbilityId::LayApMine, AbilityId::LayAtMine, AbilityId::ClearMines, AbilityId::LayWire,
                      AbilityId::PlaceHedgehogs, AbilityId::BuildPillbox, AbilityId::Demolish},
        .ability_count = 7,
    },
    {
        // A howitzer on tracks: sets up in moments, shoots and scoots.
        .name = "SPG 2S1",
        .short_name = "SPG",
        .max_hp = 200,
        .armor = {15, 15, 20},
        .speed = tiles_per_second(6, 5),
        .radius = tiles(9, 20),
        .sight = tiles(6),
        .mass = 14,
        .vehicle = true,
        .weapon = {.name = "122mm HE shell", .damage = 110, .damage_type = DamageType::Explosive,
                   .range = tiles(60), .reload = seconds(6), .projectile_speed = tiles_per_second(9),
                   .splash_radius = tiles(3, 2), .accuracy = 100, .miss_spread = tiles(0), .indirect = true,
                   .min_range = tiles(4)},
        .cost = {4, 0, 200, 60, 60},
        .train_time = seconds(40),
        .fuel_capacity = tiles(160),
        .rounds_capacity = 40,
        .abilities = {AbilityId::Deploy, AbilityId::DigGunPit, AbilityId::Camouflage, AbilityId::RadioSilence,
                      AbilityId::CallSupply},
        .ability_count = 5,
        .deploy_time = seconds(2),
        .emitter = true,
    },
    {
        // A radio on his back: silent units near him still get their orders at once.
        .name = "Signaller",
        .short_name = "SIG",
        .max_hp = 35,
        .armor = {0, 0, 45},
        .speed = tiles_per_second(1),
        .radius = tiles(1, 5),
        .sight = tiles(7),
        .mass = 1,
        .vehicle = false,
        .weapon = {.name = "Carbine", .damage = 5, .damage_type = DamageType::Bullet, .range = tiles(4),
                   .reload = seconds(5, 4), .projectile_speed = kInstantHit, .splash_radius = kNoSplash,
                   .accuracy = 60, .miss_spread = tiles(1)},
        .cost = {1, 25, 10, 10, 0},
        .train_time = seconds(15),
        .rounds_capacity = 60,
        .rounds_per_supply = 30,
        .abilities = {AbilityId::RadioSilence},
        .ability_count = 1,
        .emitter = true,
        .relay_range = tiles(6),
    },
    {
        // A command vehicle bristling with antennas: a relay on wheels, and a
        // loud one on the air.
        .name = "Command vehicle",
        .short_name = "CMD",
        .max_hp = 180,
        .armor = {8, 5, 5},
        .speed = tiles_per_second(7, 5),
        .radius = tiles(2, 5),
        .sight = tiles(7),
        .mass = 14,
        .vehicle = true,
        .wheeled = true,
        .weapon = {.name = "Unarmed", .damage = 0, .damage_type = DamageType::Bullet, .range = tiles(0),
                   .reload = seconds(1), .projectile_speed = kInstantHit, .splash_radius = kNoSplash,
                   .accuracy = 0, .miss_spread = tiles(0)},
        .cost = {2, 0, 120, 0, 40},
        .train_time = seconds(30),
        .fuel_capacity = tiles(200),
        .abilities = {AbilityId::RadioSilence, AbilityId::CallSupply},
        .ability_count = 2,
        .emitter = true,
        .relay_range = tiles(12),
    },
    {
        // Listens and never talks: a bearing on every radio in reach. Two
        // stations far enough apart cross their bearings into a fix.
        .name = "DF station",
        .short_name = "DF",
        .max_hp = 100,
        .armor = {3, 0, 0},
        .speed = tiles_per_second(8, 5),
        .radius = tiles(7, 20),
        .sight = tiles(6),
        .mass = 10,
        .vehicle = true,
        .wheeled = true,
        .weapon = {.name = "Unarmed", .damage = 0, .damage_type = DamageType::Bullet, .range = tiles(0),
                   .reload = seconds(1), .projectile_speed = kInstantHit, .splash_radius = kNoSplash,
                   .accuracy = 0, .miss_spread = tiles(0)},
        .cost = {2, 0, 120, 20, 30},
        .train_time = seconds(30),
        .abilities = {AbilityId::Deploy},
        .ability_count = 1,
        .deploy_time = seconds(5),
        .df_range = tiles(35),
    },
    {
        // Flies only on missions: a rocket run at the target, back to the
        // airfield, rearmed from the stock. Tough: takes two missile hits.
        .name = "Su-25 attack aircraft",
        .short_name = "SU25",
        .max_hp = 300,
        .armor = {5, 15, 15},
        .speed = tiles_per_second(5),
        .radius = tiles(1, 2),
        .sight = tiles(9),
        .mass = 20,
        .vehicle = true,
        .weapon = {.name = "S-8 rockets", .damage = 60, .damage_type = DamageType::Explosive, .range = tiles(9),
                   .reload = 0, .projectile_speed = tiles_per_second(25), .splash_radius = tiles(6, 5),
                   .accuracy = 100, .miss_spread = tiles(0)},
        .cost = {1, 0, 250, 80, 120},
        .train_time = seconds(60),
        .fuel_capacity = tiles(240),
        .rounds_capacity = 16,
        .aircraft = true,
    },
    {
        // A missile on the shoulder: deadly to aircraft, useless on the ground.
        .name = "MANPADS crew (Igla)",
        .short_name = "AA",
        .max_hp = 40,
        .armor = {0, 0, 45},
        .speed = tiles_per_second(1),
        .radius = tiles(1, 5),
        .sight = tiles(7),
        .mass = 1,
        .vehicle = false,
        .weapon = {.name = "Igla missile", .damage = 160, .damage_type = DamageType::Explosive, .range = tiles(10),
                   .reload = seconds(10), .projectile_speed = tiles_per_second(20), .splash_radius = kNoSplash,
                   .accuracy = 50, .miss_spread = tiles(0), .anti_air = true, .air_only = true},
        .cost = {1, 25, 0, 60, 0},
        .train_time = seconds(20),
        .rounds_capacity = 4,
    },
    {
        // Four radar-laid 23mm barrels: aircraft first, and murder on infantry.
        // Its radar is on the air; switched off, it aims by eye.
        .name = "ZSU-23-4 Shilka",
        .short_name = "ZSU",
        .max_hp = 220,
        .armor = {15, 10, 10},
        .speed = tiles_per_second(6, 5),
        .radius = tiles(9, 20),
        .sight = tiles(8),
        .mass = 20,
        .vehicle = true,
        .weapon = {.name = "23mm quad AA guns", .damage = 14, .damage_type = DamageType::Bullet, .range = tiles(7),
                   .reload = seconds(1, 4), .projectile_speed = kInstantHit, .splash_radius = kNoSplash,
                   .accuracy = 55, .miss_spread = tiles(1), .anti_air = true},
        .cost = {3, 0, 150, 80, 60},
        .train_time = seconds(35),
        .fuel_capacity = tiles(150),
        .rounds_capacity = 200,
        .rounds_per_supply = 10,
        .abilities = {AbilityId::RadioSilence, AbilityId::CallSupply},
        .ability_count = 2,
        .emitter = true,
    },
    {
        // Sees aircraft far out for the whole air defence, and is heard as
        // far: the loudest thing on the air.
        .name = "Air defence radar",
        .short_name = "RDR",
        .max_hp = 80,
        .armor = {3, 0, 0},
        .speed = tiles_per_second(7, 5),
        .radius = tiles(2, 5),
        .sight = tiles(6),
        .mass = 10,
        .vehicle = true,
        .wheeled = true,
        .weapon = {.name = "Unarmed", .damage = 0, .damage_type = DamageType::Bullet, .range = tiles(0),
                   .reload = seconds(1), .projectile_speed = kInstantHit, .splash_radius = kNoSplash,
                   .accuracy = 0, .miss_spread = tiles(0)},
        .cost = {2, 0, 150, 0, 40},
        .train_time = seconds(30),
        .abilities = {AbilityId::Deploy, AbilityId::RadioSilence},
        .ability_count = 2,
        .deploy_time = seconds(5),
        .emitter = true,
        .radar_range = tiles(45),
    },
};
static_assert(std::size(kUnitTypes) == kUnitTypeCount);

}  // namespace

const UnitTypeDef& unit_type(UnitTypeId id) { return kUnitTypes[static_cast<size_t>(id)]; }

namespace {

constexpr AbilityDef kAbilities[] = {
    {.name = "Area shot: one HE-FRAG shell with a wide burst", .label = "Area shot", .target = AbilityTarget::Point,
     .range = tiles(50), .cooldown = seconds(20),
     .weapon = {.name = "125mm HE-FRAG shell", .damage = 75, .damage_type = DamageType::Explosive,
                .range = tiles(50), .reload = seconds(4), .projectile_speed = tiles_per_second(14),
                .splash_radius = tiles(5, 4), .accuracy = 85, .miss_spread = tiles(1),
                .effective_range = tiles(15)}},
    {.name = "Switch rounds: HE / armor-piercing (reloads the gun)", .label = "HE / AP",
     .target = AbilityTarget::Instant, .range = tiles(0), .cooldown = 0},
    // Fired along the front, not aimed at anyone: whoever is in the way gets it.
    {.name = "Machine gun along the front", .label = "MG sweep", .target = AbilityTarget::Direction,
     .range = tiles(8), .cooldown = seconds(12),
     .weapon = {.name = "Coaxial machine gun", .damage = 5, .damage_type = DamageType::Bullet, .range = tiles(8),
                .reload = 0, .projectile_speed = kInstantHit, .splash_radius = kNoSplash, .accuracy = 100,
                .miss_spread = tiles(0)}},
    // Lobbed: flies over cover and comes down among the men in it.
    {.name = "Grenade launcher at an area", .label = "Grenade", .target = AbilityTarget::Point,
     .range = tiles(6), .cooldown = seconds(10),
     .weapon = {.name = "30mm grenade", .damage = 30, .damage_type = DamageType::Explosive, .range = tiles(6),
                .reload = 0, .projectile_speed = tiles_per_second(10), .splash_radius = tiles(1),
                .accuracy = 75, .miss_spread = tiles(1)}},
    {.name = "Dig a trench (drag a line)", .label = "Trench", .target = AbilityTarget::Line,
     .range = tiles(0), .cooldown = 0},
    {.name = "Dig a foxhole here: hits -50%, own accuracy -20%", .label = "Foxhole",
     .target = AbilityTarget::Instant, .range = tiles(0), .cooldown = 0},
    {.name = "Parapet facing a direction: +25% cover from the front", .label = "Parapet",
     .target = AbilityTarget::Direction, .range = tiles(0), .cooldown = 0},
    // Thrown in: into a trench, through a dugout's entrance or a window.
    {.name = "Hand grenade: into a trench, a dugout, a house", .label = "Grenade", .target = AbilityTarget::Point,
     .range = tiles(3), .cooldown = seconds(15),
     .weapon = {.name = "Hand grenade", .damage = 30, .damage_type = DamageType::Explosive, .range = tiles(3),
                .reload = 0, .projectile_speed = tiles_per_second(8), .splash_radius = tiles(1),
                .accuracy = 85, .miss_spread = tiles(1, 2)}},
    {.name = "Refill at the depot (fuel or ammunition, from the stock)", .label = "Refill",
     .target = AbilityTarget::Instant, .range = tiles(0), .cooldown = 0},
    {.name = "Deploy to fire / pack up to move (it also happens by itself)", .label = "Deploy",
     .target = AbilityTarget::Instant, .range = tiles(0), .cooldown = 0},
    {.name = "Dig in the gun: cover and concealment where it stands", .label = "Gun pit",
     .target = AbilityTarget::Instant, .range = tiles(0), .cooldown = 0},
    {.name = "Camouflage the gun: hidden until it moves (a shot still gives it away for a while)",
     .label = "Camouflage", .target = AbilityTarget::Instant, .range = tiles(0), .cooldown = 0},
    {.name = "Rapid fire: five grenades in a row along the front", .label = "Rapid fire",
     .target = AbilityTarget::Point, .range = tiles(8), .cooldown = seconds(15),
     .weapon = {.name = "30mm grenade", .damage = 20, .damage_type = DamageType::Explosive, .range = tiles(8),
                .reload = 0, .projectile_speed = tiles_per_second(9), .splash_radius = tiles(4, 5), .accuracy = 100,
                .miss_spread = tiles(0), .lobbed = true}},
    {.name = "Salvo: every rocket in the launcher at a point", .label = "Salvo", .target = AbilityTarget::Point,
     .range = tiles(70), .cooldown = 0},
    {.name = "Fire from a covered position, like artillery: each shot wears the barrel (1% HP)",
     .label = "Indirect", .target = AbilityTarget::Point, .range = tiles(60), .cooldown = 0,
     .weapon = {.name = "125mm HE shell, indirect", .damage = 75, .damage_type = DamageType::Explosive,
                .range = tiles(60), .reload = seconds(4), .projectile_speed = tiles_per_second(12),
                .splash_radius = tiles(1, 2), .accuracy = 100, .miss_spread = tiles(0), .indirect = true,
                .min_range = tiles(3)}},
    {.name = "Anti-personnel mine (5 ammunition)", .label = "AP mine", .target = AbilityTarget::Point,
     .range = tiles(0), .cooldown = 0},
    {.name = "Anti-tank mine (10 ammunition)", .label = "AT mine", .target = AbilityTarget::Point,
     .range = tiles(0), .cooldown = 0},
    {.name = "Clear the enemy mines found around a point", .label = "Clear", .target = AbilityTarget::Point,
     .range = tiles(0), .cooldown = 0},
    {.name = "Barbed wire along a line (5 materials a tile)", .label = "Wire", .target = AbilityTarget::Line,
     .range = tiles(0), .cooldown = 0},
    {.name = "Anti-tank hedgehogs along a line (10 materials a tile)", .label = "Hedgehogs",
     .target = AbilityTarget::Line, .range = tiles(0), .cooldown = 0},
    {.name = "Pillbox here, its slit facing a direction (80 materials)", .label = "Pillbox",
     .target = AbilityTarget::Direction, .range = tiles(0), .cooldown = 0},
    {.name = "Demolition charge against a building or a bridge", .label = "Charge", .target = AbilityTarget::Point,
     .range = tiles(0), .cooldown = 0},
    {.name = "Smoke screen ahead: nothing is seen through it (needs smoke grenades)", .label = "Smoke",
     .target = AbilityTarget::Instant, .range = tiles(0), .cooldown = seconds(30), .needs = UpgradeId::SmokeGrenades},
    {.name = "Radio silence: enemy direction finders lose it, but orders come by courier (3 s) away from a relay",
     .label = "Radio off", .target = AbilityTarget::Instant, .range = tiles(0), .cooldown = 0},
    {.name = "Call supply by radio: the nearest free tanker / ammunition truck comes over to top it up",
     .label = "Supply", .target = AbilityTarget::Instant, .range = tiles(0), .cooldown = seconds(5)},
    // Wire-guided: slow, but it flies after the vehicle it's aimed at.
    {.name = "ATGM (Konkurs): a guided missile at an enemy vehicle, 25 tiles (needs the launchers)",
     .label = "ATGM", .target = AbilityTarget::Point, .range = tiles(25), .cooldown = seconds(10),
     .weapon = {.name = "9M113 Konkurs", .damage = 200, .damage_type = DamageType::AntiTank, .range = tiles(25),
                .reload = seconds(4), .projectile_speed = tiles_per_second(5), .splash_radius = kNoSplash,
                .accuracy = 90, .miss_spread = tiles(2), .structure_damage = 80, .guided = true},
     .needs = UpgradeId::Atgm},
};
static_assert(std::size(kAbilities) == kAbilityCount);

}  // namespace

const AbilityDef& ability_def(AbilityId id) { return kAbilities[static_cast<size_t>(id)]; }

namespace {

// Armor is {Bullet, Explosive, AntiTank}; bullets are ignored anyway.
// Costs are {Personnel, Food, Materials, Ammo, Fuel}; build times are for one
// rear trooper (two build twice as fast).
constexpr StructureDef kStructureTypes[] = {
    // A small house: ~8 tank shells or ~20 RPG rockets bring it down.
    {.name = "House", .max_hp = 600, .armor = {0, 0, 50}, .capacity = 6},
    // Solid: blowing a bridge takes a real effort (sappers will do it faster).
    {.name = "Bridge", .max_hp = 1500, .armor = {0, 10, 60}},
    {.name = "Headquarters", .max_hp = 2500, .armor = {0, 20, 80},
     .roster = {UnitTypeId::Worker, UnitTypeId::Truck, UnitTypeId::FuelTanker, UnitTypeId::AmmoTruck},
     .roster_size = 4},
    {.name = "Infantry barracks", .max_hp = 1500, .armor = {0, 10, 60},
     .buildable = true, .width = 3, .height = 3, .cost = {0, 0, 150, 0, 0}, .build_time = seconds(30),
     .roster = {UnitTypeId::Rifleman, UnitTypeId::MachineGunner, UnitTypeId::Grenadier, UnitTypeId::Assault},
     .roster_size = 4},
    {.name = "Armor barracks", .max_hp = 2200, .armor = {0, 15, 70},
     .buildable = true, .width = 4, .height = 4, .cost = {0, 0, 250, 0, 50}, .build_time = seconds(45),
     .roster = {UnitTypeId::Tank, UnitTypeId::Ifv}, .roster_size = 2},
    // Put one next to a woodline or a quarry to cut the walk, like an AoE II lumber camp.
    {.name = "Warehouse", .max_hp = 800, .armor = {0, 5, 40},
     .buildable = true, .width = 2, .height = 2, .cost = {0, 0, 75, 0, 0}, .build_time = seconds(20)},
    // The railhead is given, not built: lose it and the trains stop coming.
    {.name = "Railway station", .max_hp = 2000, .armor = {0, 15, 60}},
    {.name = "Ammo depot", .max_hp = 900, .armor = {0, 5, 40},
     .buildable = true, .width = 2, .height = 2, .cost = {0, 0, 100, 0, 0}, .build_time = seconds(25)},
    // Flimsy, and it goes up in flames with the fuel inside.
    {.name = "Fuel depot", .max_hp = 450, .armor = {0, 0, 10},
     .buildable = true, .width = 2, .height = 2, .cost = {0, 0, 100, 0, 0}, .build_time = seconds(25)},
    {.name = "Recon barracks", .max_hp = 1000, .armor = {0, 10, 60},
     .buildable = true, .width = 2, .height = 2, .cost = {0, 0, 100, 0, 0}, .build_time = seconds(25),
     .roster = {UnitTypeId::Scout}, .roster_size = 1},
    // Field works, dug by infantry one tile at a time; shells fill them in.
    {.name = "Trench", .max_hp = 200, .armor = {0, 10, 60}, .cache_capacity = 40},
    {.name = "Foxhole", .max_hp = 150, .armor = {0, 10, 60}, .cache_capacity = 20},
    {.name = "Parapet", .max_hp = 150, .armor = {0, 10, 60}},
    // Logs and earth: holds against mortars and light shells, not against heavy ones.
    {.name = "Dugout", .max_hp = 1200, .armor = {0, 30, 80}, .capacity = 8, .cache_capacity = 150},
    {.name = "Artillery barracks", .max_hp = 1800, .armor = {0, 15, 60},
     .buildable = true, .width = 3, .height = 3, .cost = {0, 0, 200, 0, 50}, .build_time = seconds(40),
     .roster = {UnitTypeId::Mortar, UnitTypeId::Ags, UnitTypeId::Howitzer, UnitTypeId::Spg, UnitTypeId::Mlrs},
     .roster_size = 5},
    {.name = "Gun pit", .max_hp = 250, .armor = {0, 10, 60}, .cache_capacity = 80},
    {.name = "Engineer barracks", .max_hp = 1000, .armor = {0, 10, 60},
     .buildable = true, .width = 2, .height = 2, .cost = {0, 0, 120, 0, 0}, .build_time = seconds(25),
     .roster = {UnitTypeId::Sapper}, .roster_size = 1},
    // Obstacles: a shell or a tank's tracks make short work of wire.
    {.name = "Barbed wire", .max_hp = 60, .armor = {0, 0, 60}},
    {.name = "Hedgehogs", .max_hp = 400, .armor = {0, 30, 80}},
    // Logs and earth with a slit facing the enemy: bullets don't get in.
    {.name = "Pillbox", .max_hp = 1500, .armor = {0, 40, 60}, .capacity = 3, .width = 1, .height = 1,
     .cost = {0, 0, 80, 0, 0}, .build_time = seconds(30), .cache_capacity = 100},
    {.name = "Signals barracks", .max_hp = 1000, .armor = {0, 10, 60},
     .buildable = true, .width = 2, .height = 2, .cost = {0, 0, 120, 0, 0}, .build_time = seconds(25),
     .roster = {UnitTypeId::Signaler, UnitTypeId::FieldHq, UnitTypeId::DfStation}, .roster_size = 3},
    {.name = "Air defence barracks", .max_hp = 1200, .armor = {0, 10, 60},
     .buildable = true, .width = 2, .height = 2, .cost = {0, 0, 150, 0, 0}, .build_time = seconds(30),
     .roster = {UnitTypeId::Manpads, UnitTypeId::Shilka, UnitTypeId::AirRadar}, .roster_size = 3},
    // A runway with a tower: the aircraft park on it. Flat: it hides nothing.
    {.name = "Airfield", .max_hp = 2500, .armor = {0, 10, 60},
     .buildable = true, .width = 6, .height = 3, .cost = {0, 0, 300, 0, 100}, .build_time = seconds(60),
     .roster = {UnitTypeId::Su25}, .roster_size = 1},
    // Concrete panels: it takes a lot to bring down, and holds a company.
    {.name = "Apartment block", .max_hp = 4000, .armor = {0, 40, 90}, .capacity = 12},
    // A lattice mast: a few shells bring it down, and the spotter with it.
    {.name = "Cell tower", .max_hp = 300, .armor = {0, 5, 20}, .capacity = 1},
    // A shop and the pumps under a canopy; with fuel in the tanks, it goes up in flames.
    {.name = "Gas station", .max_hp = 500, .armor = {0, 5, 30}, .capacity = 3},
    // Reinforced concrete silos: very hard to bring down.
    {.name = "Grain elevator", .max_hp = 5000, .armor = {0, 50, 90}, .capacity = 6},
    // A long hut of bunks: cheap, quick, and every one of them counts.
    {.name = "Living quarters", .max_hp = 700, .armor = {0, 10, 50},
     .buildable = true, .width = 2, .height = 2, .cost = {0, 0, 50, 0, 0}, .build_time = seconds(20)},
};
static_assert(std::size(kStructureTypes) == static_cast<size_t>(StructureType::Count));

}  // namespace

const StructureDef& structure_type(StructureType type) { return kStructureTypes[static_cast<size_t>(type)]; }

namespace {

constexpr UpgradeDef kUpgrades[] = {
    {.name = "Smoke grenades", .label = "Smoke", .description = "Tanks can lay a smoke screen: nothing is seen through it",
     .building = StructureType::AmmoDepot, .cost = {0, 0, 50, 60, 0}, .time = seconds(45)},
    {.name = "Sabot rounds", .label = "Sabot", .description = "Tank armor-piercing rounds hit 30% harder",
     .building = StructureType::AmmoDepot, .cost = {0, 0, 80, 100, 0}, .time = seconds(60)},
    {.name = "Cluster rockets", .label = "Cluster", .description = "MLRS rockets burst 50% wider",
     .building = StructureType::AmmoDepot, .cost = {0, 0, 60, 120, 0}, .time = seconds(60)},
    {.name = "More trains", .label = "Schedule", .description = "A train every 45 s instead of every 60 s",
     .building = StructureType::Station, .cost = {0, 200, 150, 0, 50}, .time = seconds(90)},
    {.name = "Heavier trains", .label = "Capacity", .description = "Trains bring 50% more",
     .building = StructureType::Station, .cost = {0, 200, 200, 0, 50}, .time = seconds(90)},
    {.name = "Optics", .label = "Optics",
     .description = "Scouts make out men in cover 2 tiles farther; posts watch 3 tiles farther",
     .building = StructureType::ReconBarracks, .cost = {0, 0, 60, 40, 0}, .time = seconds(45)},
    {.name = "Entrenching tools", .label = "Shovels", .description = "Riflemen dig a third faster",
     .building = StructureType::InfantryBarracks, .cost = {0, 0, 60, 0, 0}, .time = seconds(30)},
    {.name = "Reactive armor (Kontakt-5)", .label = "ERA",
     .description = "Tanks take 35% less from anti-tank hits: RPGs, AP rounds, missiles",
     .building = StructureType::ArmorBarracks, .cost = {0, 0, 150, 100, 0}, .time = seconds(60)},
    {.name = "Fire control system", .label = "FCS",
     .description = "Tank guns keep their aim far out: 65% of it at 50 tiles instead of 35%",
     .building = StructureType::ArmorBarracks, .cost = {0, 0, 120, 60, 0}, .time = seconds(60)},
    {.name = "ATGM launchers (Konkurs)", .label = "ATGM",
     .description = "IFVs fire a guided anti-tank missile, 25 tiles; 4 aboard, ammunition trucks bring more",
     .building = StructureType::ArmorBarracks, .cost = {0, 0, 100, 150, 0}, .time = seconds(60)},
    {.name = "Firing tables", .label = "Tables",
     .description = "Ranging in goes faster: 30/70/95% on target instead of 17/50/95%",
     .building = StructureType::ArtilleryBarracks, .cost = {0, 0, 80, 40, 0}, .time = seconds(45)},
    {.name = "Drilled crews", .label = "Drill", .description = "Guns set up and pack up twice as fast",
     .building = StructureType::ArtilleryBarracks, .cost = {0, 100, 60, 0, 0}, .time = seconds(45)},
    {.name = "Long-range charges", .label = "Charges",
     .description = "Howitzers, SPGs and mortars reach 25% farther",
     .building = StructureType::ArtilleryBarracks, .cost = {0, 0, 100, 150, 0}, .time = seconds(60)},
    {.name = "Body armor", .label = "Armor", .description = "Foot soldiers take 25% less from bullets and fragments",
     .building = StructureType::InfantryBarracks, .cost = {0, 0, 120, 0, 0}, .time = seconds(50)},
    {.name = "Load-bearing vests", .label = "Vests", .description = "Foot soldiers carry 50% more rounds",
     .building = StructureType::InfantryBarracks, .cost = {0, 50, 80, 0, 0}, .time = seconds(40)},
    {.name = "Ghillie suits", .label = "Ghillie",
     .description = "Scouts in cover are made out only from half as close",
     .building = StructureType::ReconBarracks, .cost = {0, 0, 50, 0, 0}, .time = seconds(30)},
    {.name = "Heavier charges", .label = "Charges", .description = "Mines and demolition charges hit 50% harder",
     .building = StructureType::EngineerBarracks, .cost = {0, 0, 60, 80, 0}, .time = seconds(45)},
    {.name = "Prefab pillboxes", .label = "Prefab", .description = "Pillboxes go up twice as fast",
     .building = StructureType::EngineerBarracks, .cost = {0, 0, 100, 0, 0}, .time = seconds(45)},
    {.name = "Secure radios (ZAS)", .label = "ZAS",
     .description = "Enemy direction finders need three bearings, not two, to fix our radios",
     .building = StructureType::SignalsBarracks, .cost = {0, 0, 100, 0, 0}, .time = seconds(60)},
    {.name = "Mast antennas", .label = "Masts",
     .description = "The headquarters and command vehicles relay orders 50% farther",
     .building = StructureType::SignalsBarracks, .cost = {0, 0, 80, 0, 20}, .time = seconds(45)},
    {.name = "Radar tracking", .label = "Tracking",
     .description = "Shilkas and MANPADS are 20% more accurate against aircraft",
     .building = StructureType::AirDefenseBarracks, .cost = {0, 0, 100, 50, 0}, .time = seconds(50)},
    {.name = "Cockpit armor", .label = "Armor", .description = "Su-25s take 30% less damage (about 40% tougher)",
     .building = StructureType::Airfield, .cost = {0, 0, 150, 0, 50}, .time = seconds(60)},
};
static_assert(std::size(kUpgrades) == kUpgradeCount);

}  // namespace

const UpgradeDef& upgrade_def(UpgradeId id) { return kUpgrades[static_cast<size_t>(id)]; }

}  // namespace engine
